# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np
import pandas as pd


In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()

a2 = np.array([
    [1,2,3],
    [4,5,6]
])
# Create a 3-dimensional Numpy array using np.array()

a3 = np.array([
    [[1,2,3], [4,5,6]],
    [[7,8,9], [10,11,12]],
    [[13,14,15], [16,17,18]]
])



In [3]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(3,)
(2, 3)
(3, 2, 3)


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [6]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((3, 2, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
a1_df = pd.DataFrame(a2)
a1_df

,0,1,2
0,1,2,3
1,4,5,6


In [8]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
# Create an array within a range of 0 and 100 with step 3
array_with_step3 = np.arange(0,100, step=3)
array_with_step3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
intBetweenZeroToTen = np.random.randint(0,10, size=(7,2))
intBetweenZeroToTen

array([[0, 3],
       [1, 4],
       [9, 4],
       [2, 8],
       [4, 4],
       [1, 4],
       [3, 5]], dtype=int32)

In [12]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
floatBetweenZeroAndOne= np.random.rand(3,5)
floatBetweenZeroAndOne

array([[0.43024322, 0.51324933, 0.9809197 , 0.8354993 , 0.18288765],
       [0.83084737, 0.45073134, 0.67394273, 0.73421348, 0.43392596],
       [0.70630252, 0.04025653, 0.05286459, 0.56863707, 0.51892916]])

In [13]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
seedRandom =  np.random.randint(0,10, size=(4,6))
seedRandom

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [14]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
randomNumbersToFindUnique = np.random.randint(1,10,size=(3,7))
print(randomNumbersToFindUnique)

# Find the unique numbers in the array you just created
np.unique(randomNumbersToFindUnique)

[[9 1 3 7 4 9 3]
 [5 3 7 5 9 7 2]
 [4 9 2 9 5 2 4]]


array([1, 2, 3, 4, 5, 7, 9], dtype=int32)

In [15]:
# Find the 0'th index of the latest array you created
randomNumbersToFindUnique[0]

array([9, 1, 3, 7, 4, 9, 3], dtype=int32)

In [16]:
# Get the first 2 rows of latest array you created
randomNumbersToFindUnique[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]], dtype=int32)

In [17]:
# Get the first 2 values of the first 2 rows of the latest array
randomNumbersToFindUnique[:2, :2]

array([[9, 1],
       [5, 3]], dtype=int32)

In [18]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
sum1 = np.random.randint(0, 10, size=(3,5))
print(sum1)
sum2 = np.ones(shape=(3,5))
print(sum2)

[[6 7 2 0 3]
 [1 7 3 1 5]
 [5 9 3 5 1]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
# Add the two arrays together
totalSumAdd = np.add(sum1, sum2)
print(totalSumAdd)
totalSum = np.sum(sum1)
print(totalSum)

[[ 7.  8.  3.  1.  4.]
 [ 2.  8.  4.  2.  6.]
 [ 6. 10.  4.  6.  2.]]
58


In [20]:
# Create another array of ones of shape (5, 3)
onesShape5_3 = np.ones(shape=(5,3))
onesShape5_3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
# Try add the array of ones and the other most recent array together
AfterAddingTranspose = totalSumAdd+onesShape5_3.T
AfterAddingTranspose

array([[ 8.,  9.,  4.,  2.,  5.],
       [ 3.,  9.,  5.,  3.,  7.],
       [ 7., 11.,  5.,  7.,  3.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [22]:
# Create another array of ones of shape (3, 5)
toSubDay = np.ones(shape=(3,5))
toSubDay


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
# Subtract the new array of ones from the other most recent array
afterSubtract = AfterAddingTranspose - toSubDay
afterSubtract

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [24]:
# Multiply the ones array with the latest array
multipliedArray = AfterAddingTranspose * sum2
multipliedArray

array([[ 8.,  9.,  4.,  2.,  5.],
       [ 3.,  9.,  5.,  3.,  7.],
       [ 7., 11.,  5.,  7.,  3.]])

In [25]:
# Take the latest array to the power of 2 using '**'
exponentMultiplication = multipliedArray ** 2
exponentMultiplication

array([[ 64.,  81.,  16.,   4.,  25.],
       [  9.,  81.,  25.,   9.,  49.],
       [ 49., 121.,  25.,  49.,   9.]])

In [26]:
# Do the same thing with np.square()
np.square(multipliedArray)

array([[ 64.,  81.,  16.,   4.,  25.],
       [  9.,  81.,  25.,   9.,  49.],
       [ 49., 121.,  25.,  49.,   9.]])

In [27]:
# Find the mean of the latest array using np.mean()
np.mean(exponentMultiplication)

np.float64(41.06666666666667)

In [28]:
# Find the maximum of the latest array using np.max()
np.max(exponentMultiplication)

np.float64(121.0)

In [29]:
# Find the minimum of the latest array using np.min()
np.min(exponentMultiplication)

np.float64(4.0)

In [30]:
# Find the standard deviation of the latest array
np.std(exponentMultiplication)

np.float64(32.81761044859231)

In [31]:
# Find the variance of the latest array
np.var(exponentMultiplication)

np.float64(1076.9955555555555)

In [32]:
# Reshape the latest array to (3, 5, 1)
np.reshape(toSubDay, shape=(3,5,1))

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [33]:
# Transpose the latest array
exponentMultiplication.T

array([[ 64.,   9.,  49.],
       [ 81.,  81., 121.],
       [ 16.,  25.,  25.],
       [  4.,   9.,  49.],
       [ 25.,  49.,   9.]])

What does the transpose do?

In [34]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
rand1 = np.random.randint(0,10, size=(3,3))
rand2 = np.random.randint(0,10, size=(3,2))
print(rand1)
print(rand2)

[[9 1 9]
 [3 7 6]
 [8 7 4]]
[[1 4]
 [7 9]
 [8 8]]


In [35]:
# Perform a dot product on the two newest arrays you created
dotMultiplication = np.dot(rand1,rand2)
print(dotMultiplication)

[[ 88 117]
 [100 123]
 [ 89 127]]


In [36]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
rand3 = np.random.randint(0,10, size=(4,3))
rand4 = np.random.randint(0, 10, size=(4,3))
print(rand3)
print(rand4)

[[0 8 6]
 [8 7 0]
 [7 7 2]
 [0 7 2]]
[[2 0 4]
 [9 6 9]
 [8 6 8]
 [7 1 0]]


In [37]:
# Perform a dot product on the two newest arrays you created
dotMultiplication2 = np.dot(rand3, rand4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
dotMultiplication2 = np.dot(rand3, rand4.T)
print(dotMultiplication2)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [40]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
randomInts1 = np.random.randint(0, 10, size=(2,2))
randomInts2 = np.random.randint(0,10, size=(2,2))
print(randomInts1)
print(randomInts2)

[[2 7]
 [5 2]]
[[0 2]
 [4 2]]


In [41]:
# Compare the two arrays with '>'

randomInts1 > randomInts2

array([[ True,  True],
       [ True, False]])

What happens when you compare the arrays with `>`?

In [42]:
# Compare the two arrays with '>='
randomInts1 >= randomInts2

array([[ True,  True],
       [ True,  True]])

In [43]:
# Find which elements of the first array are greater than 7
randomInts1 > 7

array([[False, False],
       [False, False]])

In [44]:
# Which parts of each array are equal? (try using '==')
randomInts1 == randomInts2

array([[False, False],
       [False,  True]])

In [45]:
# Sort one of the arrays you just created in ascending order
np.sort(randomInts1)

array([[2, 7],
       [2, 5]], dtype=int32)

In [48]:
# Sort the indexes of one of the arrays you just created
randomInts1


array([[2, 7],
       [5, 2]], dtype=int32)

In [49]:
np.argsort(randomInts1)

array([[0, 1],
       [1, 0]])

In [51]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(randomInts1)

np.int64(1)

In [52]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(randomInts1)

np.int64(0)

In [60]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
customArray = np.array([[1, 2], [3,4]])
np.max(customArray, axis=1)

array([2, 4])

In [61]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.min(customArray, axis=0)

array([1, 2])

In [63]:
# Create an array of normally distributed random numbers
ND_array = np.random.randn(3,5)
ND_array

array([[-0.50175704,  0.91540212,  0.32875111, -0.5297602 ,  0.51326743],
       [ 0.09707755,  0.96864499, -0.70205309, -0.32766215, -0.39210815],
       [-1.46351495,  0.29612028,  0.26105527,  0.00511346, -0.23458713]])

In [67]:
# Create an array with 10 evenly spaced numbers between 1 and 100
evenlySpacedArray = np.linspace(1, 100, 10)
evenlySpacedArray

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.